storage:
  enable: true
  path: "./data/media"
db:
  type: "sqlite"
  path: "./data/db.sqlite"
  # host: "localhost"
  # port: 8022
  # user: "user"
  # password: "password"
  # database: "zcms"
http:
  cookie_secret: "cookie_secret"
  port: 8080
  credentials: null
  # credentials:
  #   key: "path-to-key"
  #   cert: "path-to-cert"
  #   ca: "path-to-ca"
  # cors:
  #   origin:
  #     - "http://localhost:8080"
  #   methods:
  #     - GET
  #     - POST
  #     - PUT
  #     - DELETE
auth:
  enable: true
  jwt_secret: "jwt_secret"
  secure_cookies: false
localization:
  enable: true
  locales: ["ru", "en"]
  fallbackLocale: "en"