# table users will be created automatically, if auth.enable = true
# localized values will be created automatically, if localization.enable = true
# table media will be created automatically, if storage.enable = true

tables:
  - name: pages
    fields:
    - name: name
      type: "VARCHAR(300)"
      required: true
      unique: true
    - name: content
      type: "json"
      required: true
      localized: true
    - name: author
      type: "VARCHAR(255)"
      relation:
        table: "users"
        column: "login"
        kind: many-to-one
        onDelete: setNull